### ISSUE TITLE
Error when latest release goes to second page

### ISSUE THREAD

**Issue by rez0n** [pozetroninc/github-action-get-latest-release#13]
Hi, Thank you for this very useful action.
Seems when latest stable release goest to the second page, action does not see them.

My configuration

```
      - id: NodeBB-stable
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: NodeBB
            repo: NodeBB
            excludes: prerelease, draft
```

But this works good.
```
      - id: NodeBB-beta
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: NodeBB
            repo: NodeBB
```

Link to the releases page https://github.com/NodeBB/NodeBB/releases
3 days ago I have [successful](https://github.com/rez0n/docker-nodebb/actions) builds
