### ISSUE TITLE
Don't return draft release. Is it normal?

### ISSUE THREAD

**Issue by fboucher** [pozetroninc/github-action-get-latest-release#15]
The latest release is a draft but is never returned.
I also tried with only a draft and it doesn't return anything. I get the message "No valid releases"

```yaml
name: Build Docker Images
on: [push]
jobs:
  build:
    name: cloudbot-beta
    runs-on: ubuntu-latest
    steps:
    - id: vars
      uses: pozetroninc/github-action-get-latest-release@master
      with:
          owner: FBoucher
          repo: CloudBot
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{secrets.DOCKER_USER}}/cloudbot
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.vars.outputs.release }}-beta"
```
