### ISSUE TITLE
Unable to use output in other action

### ISSUE THREAD

**Issue by davidsneighbour** [pozetroninc/github-action-get-latest-release#17]
I am trying to set up a workflow where a version number is updated in a toml file. The relevant setup is as follows:

```yaml
    steps:
      - id: gohugohugo
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: gohugoio
          repo: hugo
          excludes: prerelease, draft
      - uses: actions/checkout@v2
      - uses: ciiiii/toml-editor@1.0.0
        with:
          file: netlify.toml
          key: context.production.environment.HUGO_VERSION
          value: ${{ steps.gohugohugo.outputs.release }}
```

I can confirm, that the setup of toml-editor catches the proper file (on the first try it added some indentation to the file) but it does not add the proper new version number from the gohugo repo, but just replaces the current version. Is it possible that subsequent actions have no access to step.id.outputs or do I overlook something? 

I tried adding the output with `"${{ steps.gohugohugo.outputs.release }}"` with the same result.

The full action setup is at https://github.com/davidsneighbour/kollitsch.de/blob/main/.github/workflows/update-netlify.yml

I set the action runner to debugging and it echoed:

```
 ::set-output name=release::v0.89.4
```

which is the right latest version, but running the action leaves the version at 0.88.1.
