### ISSUE TITLE
Inputs missing

### ISSUE THREAD

**Issue by laszabine** [pozetroninc/github-action-get-latest-release#2]
I'm using your action in my workflow like so: 
```
jobs: 
  x: 
    steps: 
      - name: "Read latest release version"
        id: read-latest-release-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: ${{ github.repository }}
``` 
and I receive the following error: 
```
##[warning]Unexpected input 'repository', valid inputs are ['']
Run pozetroninc/github-action-get-latest-release@master
  with:
    repository: rarusel/terra-snellman
##[error]Cannot read property 'tag_name' of undefined
```
I don't know much about actions/workflows yet, but this seems consistent with the fact that your `action.yaml` does not list any input parameters. 
If this is indeed the source of my problem, would you mind fixing it? 
If not, do you have any recommendations why else I might be getting this error? 
Thanks!
