### ISSUE TITLE
Get latest stable

### ISSUE THREAD

**Issue by rez0n** [pozetroninc/github-action-get-latest-release#5]
Hi, thanks for the action. 
Would be great if it was possible to get **latest** stable release, because some projects have a lot of _beta_ releases at the top.

**Comment by neil-pozetroninc** [comment]
We could add something like that. I'm thinking of doing it like this:

You can add another input called `excludes` which would be a list of release attributes you don't want to see.
```
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: pozetroninc
            repo: github-action-get-latest-release
            excludes: prerelease, draft
```
```
var excludes = core.getInput('excludes').trim().split(",");
...
        if (excludes.includes('prerelease')) {
            releases = releases.filter(x => x.prerelease != true);
        }
        if (excludes.includes('draft')) {
            releases = releases.filter(x => x.draft != true);
        }
```

This wouldn't change the default behavior and would allow people that care to exclude anything that's not a "stable" release.
