### ISSUE TITLE
Feature: Get last `n` releases || releases compatible with semver range

### ISSUE THREAD

**Issue by LongLiveCHIEF** [pozetroninc/github-action-get-latest-release#6]
Often if you're doing something like building a docker image around a product (for me it's the official octoprint/octoprint image), then you need to not only build an image for the latest release of a product, but several of the previous releases.

It would be great to be able to specify the last `n` releases, or to specify a semver input and get all tags that match.

**Comment by LongLiveCHIEF** [comment]
I'm willing to help by contributing this feature if you like the idea.  I was actually going to create this "get release" action, and figured I'd search the marketplace first.  Ironically, @foosel is a contributor to this action, and she's the maintainer of the product I'm supporting docker images for!

I also recently released the `HackerHappyHour/tagging-strategy` action, which would pair with this nicely using the output.  It's possible we could even create a compound action to get matching releases and create a matrix of tags.

**Comment by LongLiveCHIEF** [comment]
Here's what I'm thinking this could look like: (see example of creating a matrix in one job and passing it to another from [github actions docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-6)

```yaml
jobs:
  releases:
    outputs:
      matrix: ${{ steps.releases.outputs.matrix }}
    steps:
      # produces a matrix with a key of `matrix`
      - name: Get Releases
         id: releases
         uses: pozetroninc/github-action-get-latest-release
          with: 
            repository: some/repository
            semver: '^1.0.0'
  build:
    needs: releases
    strategy: 
      matrix: ${{ needs.releases.outputs.matrix }}
```
